name: Android CMake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: 26.1.10909125
      ANDROID_API_LEVEL: 21
      ANDROID_ABI: arm64-v8a
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.0'
      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}
      - name: Configure CMake for Android
        run: |
          cmake -S . -B build/android \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ env.ANDROID_ABI }} \
            -DANDROID_PLATFORM=android-${{ env.ANDROID_API_LEVEL }}
      - name: Build
        run: |
          cmake --build build/android --config Release
      - name: Run CTest (if applicable)
        run: |
          cd build/android
          ctest --output-on-failure || echo "No tests found or failed"
