name: FreeBSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: FreeBSD-vm
      uses: vmactions/freebsd-vm@v1.2.1
      with:
        usesh: true
        prepare: |
          pkg install -y cmake gmake curl

        run: |
          cmake -S . -B build
          cmake --build build
          ctest --test-dir build --output-on-failure
