name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: To build and test in FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y cmake gmake curl

        run: |
          cmake -S . -B build
          cmake --build build
          ctest --test-dir build --output-on-failure
